### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by romkhot** [thequackdaddy/tweedie#3]
**I got this message (Python 3.8, NumPy 1.20):**

c:\users\usr001\\.conda\envs\py38-env\lib\site-packages\tweedie\tweedie_dist.py:344: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

  j = np.arange(j_low, j_hi + 1, dtype=np.float)

-- Docs: https://docs.pytest.org/en/stable/warnings.html

**Possible fix** for lines 344, 396 in [tweedie_dist.py](https://github.com/thequackdaddy/tweedie/blob/master/tweedie/tweedie_dist.py)
Replace `dtype=np.float` with `dtype=np.float64`

**Comment by thequackdaddy** [comment]
closed by #7
