### ISSUE TITLE
Scipy > 1.6.3 failing test suite with index error

### ISSUE THREAD

**Issue by jmahlik** [thequackdaddy/tweedie#4]
Upgrading to scipy 1.7.0 causes tests (and code) to fail with `IndexError`s in the `tweedie/tests/test_tweedie.py::test_cdf_to_ppf`.

Running the test suite on scipy 1.6.3 works as expected. numpy version `1.21.1`. Downgrading numpy versions does not appear to have an impact, so suspecting this is solely related to the recent scipy 1.7.0 release.

I haven't quite tracked down the exact cause yet. Getting this issue out here to start the conversation and research. 

[scipy release notes](https://docs.scipy.org/doc/scipy/reference/release.1.7.0.html#id1)

```python
IndexError: boolean index did not match indexed array along dimension 0; dimension is 20 but
 corresponding boolean dimension is 1
```

**Comment by thequackdaddy** [comment]
closed by #5
